doctrine:
    dbal:
        default_connection: silenus
        connections:
            silenus:
                url: '%env(resolve:DATABASE_SLNS_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                mapping_types:
                    enum: string
            insidiome:
                url: '%env(resolve:DATABASE_NSDM_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                mapping_types:
                    enum: string

    orm:
        default_entity_manager: silenus
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        
        entity_managers:
            silenus:
                connection: silenus
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            
            insidiome:
                connection: insidiome
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
        
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
