version: '3.8'

services:
  # Apache + PHP
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: symfony_web
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DATABASE_SLNS_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_SLNS_NAME}?serverVersion=mariadb-10.11.2&charset=utf8mb4
      - DATABASE_NSDM_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NSDM_NAME}?serverVersion=mariadb-10.11.2&charset=utf8mb4
      - APP_ENV=${APP_ENV:-dev}
      - APP_SECRET=${APP_SECRET}
    depends_on:
      - db
    networks:
      - symfony_network

  # MariaDB
  db:
    image: mariadb:10.11
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony_network

  # Node pour les assets
  node:
    image: node:20-alpine
    container_name: symfony_node
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run watch"
    ports:
      - "${NODE_PORT:-5173}:5173"
    networks:
      - symfony_network

  # phpMyAdmin (optionnel)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      - db
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
