# pods/node/pod.yml
# Configuration du pod Node.js 20 (build assets)

apiVersion: v1
kind: Pod
metadata:
  name: symfony-node-pod
  labels:
    app: symfony-multi
    service: node
    category: build
spec:
  containers:
  - name: symfony-node
    image: docker.io/library/node:20-alpine
    ports:
    - containerPort: 5173
      hostPort: 6904
    workingDir: /app
    command: ["sh", "-c", "npm install && npm run watch"]
    env:
    - name: NODE_ENV
      value: "development"
    volumeMounts:
    - name: symfony-code
      mountPath: /app
    - name: node-modules
      mountPath: /app/node_modules
  volumes:
  - name: symfony-code
    hostPath:
      path: /home/sam/Bureau/dev/production/smfn_73_multi
      type: Directory
  - name: node-modules
    hostPath:
      path: /home/sam/Bureau/dev/production/smfn_73_multi/pods/node/data/node_modules
      type: DirectoryOrCreate
  restartPolicy: Always
