# pods/fastapi/pod.yml
# Configuration du pod FastAPI (API Python)

apiVersion: v1
kind: Pod
metadata:
  name: symfony-fastapi-pod
  labels:
    app: symfony-multi
    service: fastapi
    category: optional
spec:
  containers:
  - name: symfony-fastapi
    image: docker.io/tiangolo/uvicorn-gunicorn-fastapi:python3.11
    ports:
    - containerPort: 80
      hostPort: 6906
    env:
    - name: QDRANT_HOST
      value: "qdrant"
    - name: QDRANT_PORT
      value: "6333"
    - name: MODULE_NAME
      value: "main"
    - name: VARIABLE_NAME
      value: "app"
    volumeMounts:
    - name: fastapi-app
      mountPath: /app
    - name: fastapi-data
      mountPath: /app/data
    - name: fastapi-config
      mountPath: /app/config
  volumes:
  - name: fastapi-app
    hostPath:
      path: ${PODS_DIR}/fastapi/app
      type: DirectoryOrCreate
  - name: fastapi-data
    hostPath:
      path: ${PODS_DIR}/fastapi/data
      type: DirectoryOrCreate
  - name: fastapi-config
    hostPath:
      path: ${PODS_DIR}/fastapi/config
      type: DirectoryOrCreate
  restartPolicy: Always
