# pods/composer/pod.yml
# Configuration du pod Composer (utilitaire)

apiVersion: v1
kind: Pod
metadata:
  name: symfony-composer-pod
  labels:
    app: symfony-multi
    service: composer
    category: utility
spec:
  containers:
  - name: symfony-composer
    image: docker.io/library/composer:latest
    command: ["tail", "-f", "/dev/null"]
    workingDir: /app
    volumeMounts:
    - name: symfony-code
      mountPath: /app
    - name: composer-cache
      mountPath: /tmp/cache
  volumes:
  - name: symfony-code
    hostPath:
      path: ${SYMFONY_ROOT}
      type: Directory
  - name: composer-cache
    hostPath:
      path: ${PODS_DIR}/composer/data/cache
      type: DirectoryOrCreate
  restartPolicy: Always
